#! /bin/sh
  
  pgrep -x sxhkd > /dev/null || sxhkd &
  
  #bspc monitor -d I II III IV V VI VII VIII IX X
  
  bspc config border_width 5
  bspc config focused_border_color \#F9F9FB
  bspc config normal_border_color \#D2D8E0
  #bspc config window_gap          12
  
  bspc monitor HDMI-0 -d 1 2 3 4 5
  bspc monitor DVI-1 -d 6 7 8 9 0
  
  bspc config split_ratio          0.52
  bspc config borderless_monocle   true
  bspc config gapless_monocle      true
  
  bspc rule -a Gimp desktop='^8' state=floating follow=on
  bspc rule -a Chromium desktop='^2'
  bspc rule -a mplayer2 state=floating
  bspc rule -a Kupfer.py focus=on
  bspc rule -a Screenkey manage=off
  
  bspc config top_padding 0
  bspc config left_padding 0
  bspc config right_padding 0
  bspc config bottom_padding 45
  #feh --bg-fill /home/htecgeass/Downloads/nyartix-rice/wallpaper/nya.png
  # Autostart
  $HOME/.screenlayout/screen.sh &
  #picom &
  nitrogen --restore &
  $HOME/.config/polybar/launch.sh &
  bspc config focus_follows_pointer true
  #picom --experimental-backends &
  bspc config border_width 0
  #xrandr --auto --output DVI-1 --mode 1920x1080
  picom --experimental-backends &
  #bspc config border_width 0
  bspc config pointer_follows_monitor true
  #bspc desktop -m next --follow
